lib/the_little_thinkers_space_web/router.ex
defmodule TheLittleThinkersSpaceWeb.Router do
  use TheLittleThinkersSpaceWeb, :router

  import TheLittleThinkersSpaceWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TheLittleThinkersSpaceWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TheLittleThinkersSpaceWeb do
    pipe_through :browser

  
  end

  # Other scopes may use custom stacks.
  # scope "/api", TheLittleThinkersSpaceWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: TheLittleThinkersSpaceWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", TheLittleThinkersSpaceWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/", PageController, :index
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", TheLittleThinkersSpaceWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
    get "/home", PageController, :home
    resources "/users/admin", UserController
    resources "/profiles", ProfileController
    get "/add_crew_request", AddCrewRequestController, :new
    post "/add_crew_request", AddCrewRequestController, :create
    get "/remove_crew_request", RemoveCrewRequestController, :new
    post "/remove_crew_request", RemoveCrewRequestController, :create

    resources "/little_thinkers", LittleThinkerController do
      resources "/uploads", UploadController
      resources "/crew", CrewController, only: [:index]
    end
  end

  scope "/", TheLittleThinkersSpaceWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end

  scope "/", TheLittleThinkersSpaceWeb do
    pipe_through :browser

    get "/contact", ContactController, :new
    post "/contact", ContactController, :create
  end
end

lib/the_little_thinkers_space_web/controllers/crew_controller.ex
defmodule TheLittleThinkersSpaceWeb.CrewController do
  @moduledoc """
  This controller handles the users with the role Crew in relation to The Little Thinker
  """
  use TheLittleThinkersSpaceWeb, :controller
  alias TheLittleThinkersSpace.{Accounts, Accounts.Relationship}

  action_fallback TheLittleThinkersSpaceWeb.FallbackController

  def index(conn, %{"little_thinker_id" => little_thinker_id}) do
    user = conn.assigns.current_user
    little_thinker_id = String.to_integer(little_thinker_id)
    little_thinker = Accounts.get_user!(little_thinker_id)

    relationship_type =
      conn.assigns
      |> Map.get(:relationship_type, nil)
      |> case do
        nil -> Accounts.get_relationship_type(little_thinker_id, user.id)
        relationship_type -> relationship_type
      end

    with :ok <- Bodyguard.permit(Relationship, :index, user, {little_thinker, relationship_type}) do
      case user.id === little_thinker_id do
        true ->
          render(conn, "index.html",
            little_thinker: little_thinker,
            crews: user.crews,
            relationship_type: relationship_type
          )

        _ ->
          %{crews: crews} = Accounts.get_little_thinker_crew(little_thinker)

          render(conn, "index.html",
            little_thinker: little_thinker,
            crews: crews,
            relationship_type: relationship_type,
            current_user: user
          )
      end
    end
  end
end

lib/the_little_thinkers_space_web/views/crew_view.ex
defmodule TheLittleThinkersSpaceWeb.CrewView do
  use TheLittleThinkersSpaceWeb, :view

  alias TheLittleThinkersSpace.{Accounts, Accounts.Profile}

  def display_profile_link(crew_id) do
    case Accounts.get_user_profile(crew_id) do
      %Profile{} = profile ->
        profile_id = to_string(profile.id)
        link("SHOW", to: "/profiles/" <> profile_id)

      _ ->
        content_tag(:a, "NOTHING TO SEE YET")
    end
  end
end

lib/the_little_thinkers_space_web/templates/crew/index.html.heex
<body class="bg-colors bg-cover">
  <h1 class="w-screen text-sky-900 font-bold text-center text-4xl p-4 mt-8">The Crew</h1>

  <section class="flex flex-col items-center pt-8 w-screen h-full">
    <table class="xs:w-11/12 md:w-8/12 lg:w-6/12 rounded shadow-xl bg-orange-200 bg-opacity-70 overflow-hidden">
      <thead class="bg-orange-400 bg-opacity-70 rounded text-gray-900 font-bold md:text-lg">
        <tr>
          <th class="text-left p-2">First name</th>
          <th class="text-left p-2">Last name</th>
          <th class="text-left p-2"></th>
        </tr>
      </thead>

      <tbody class="divide-y divide-gray-300">
        <%= for crew <- @crews do %>
          <tr>
            <td class="text-left text-gray-900 p-2 font-semibold"><%= crew.first_name %></td>
            <td class="text-left text-gray-900 p-2"><%= crew.last_name %></td>
            <%= if @current_user.role in ["The Little Thinker", "Admin"] do %>
              <td class="text-gray-600 text-xs uppercase font-semibold tracking-wide p-2"><%= display_profile_link(crew.id) %></td>
            <% else %>
              <td></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <p class="mx-8 sm:mx-16 mt-6 text-gray-900">Please click <%= link("HERE", to: Routes.add_crew_request_path(@conn, :new), class: "text-gray-600 text-s uppercase font-semibold tracking-wide") %> if you would like to add a new member to your crew.</p>
    <p class="mx-8 sm:mx-16 mb-6 text-gray-900">Please click <%= link("HERE", to: Routes.remove_crew_request_path(@conn, :new), class: "text-gray-600 text-s uppercase font-semibold tracking-wide") %> if you would like to remove someone from the your crew.</p>
  </section>

  <div class="mx-8 sm:mx-16 my-6">
    <span class="text-sky-900 text-lg font-semibold tracking-wide"><%= link("Back", to: Routes.little_thinker_path(@conn, :show, @little_thinker)) %></span>
  </div>
</body>