lib/the_little_thinkers_space_web/router.ex
defmodule TheLittleThinkersSpaceWeb.Router do
  use TheLittleThinkersSpaceWeb, :router

  import TheLittleThinkersSpaceWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TheLittleThinkersSpaceWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TheLittleThinkersSpaceWeb do
    pipe_through :browser

  
  end

  # Other scopes may use custom stacks.
  # scope "/api", TheLittleThinkersSpaceWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: TheLittleThinkersSpaceWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", TheLittleThinkersSpaceWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/", PageController, :index
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", TheLittleThinkersSpaceWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
    get "/home", PageController, :home
    resources "/users/admin", UserController
    resources "/profiles", ProfileController
    get "/add_crew_request", AddCrewRequestController, :new
    post "/add_crew_request", AddCrewRequestController, :create
    get "/remove_crew_request", RemoveCrewRequestController, :new
    post "/remove_crew_request", RemoveCrewRequestController, :create

    resources "/little_thinkers", LittleThinkerController do
      resources "/uploads", UploadController
      resources "/crew", CrewController, only: [:index]
    end
  end

  scope "/", TheLittleThinkersSpaceWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end

  scope "/", TheLittleThinkersSpaceWeb do
    pipe_through :browser

    get "/contact", ContactController, :new
    post "/contact", ContactController, :create
  end
end

lib/the_little_thinkers_space_web/templates/page/home.html.heex
<body class="bg-colors bg-cover">
  <h1 class="w-screen text-sky-900 font-bold text-center text-4xl p-4 mt-8">
    <%= gettext("Hello %{name}!", name: @current_user.first_name) %>
  </h1>

  <p class="w-screen p-4 text-sky-900 text-center text-lg mt-8">Welcome to the Little Thinker's Space.<br /> What do you want to do?!</p>
  <div class="mt-4 mb-48 flex justify-center w-screen">
    <%= if @current_user.role == "The Little Thinker" do %>
      <%= link("Enter your own space", to: Routes.little_thinker_path(@conn, :show, @current_user), class: "btn-page") %>
    <% else %>
    <% end %>
    <%= link("Choose a Little Thinker", to: Routes.little_thinker_path(@conn, :index), class: "btn-page") %>
  </div>
</body>

lib/the_little_thinkers_space_web/templates/page/index.html.heex
<body class="bg-sky-200">
  <h1 class="w-screen text-sky-900 font-bold text-center text-4xl p-4 mt-8">
    <%= gettext("Welcome to %{name}!", name: "The Little Thinker's Space") %>
  </h1>

  <p class="w-screen p-4 text-sky-900 text-center text-lg">A safe space for your child to upload their content.<br /> Please click on the Contact button below if you have any questions.</p>

  <div class="mt-4 flex justify-center w-screen">
    <%= link("Log in", to: Routes.user_session_path(@conn, :new), class: "btn-index") %>
    <%= link("Contact", to: Routes.contact_path(@conn, :new), class: "btn-index") %>
  </div>

  <div class="mt-4 flex justify-center w-screen mt-28 px-2">
    <iframe class="rounded-lg align-center" width="854" height="480" src="https://youtube.com/embed/JHS-o0Ycy5A"></iframe>
  </div>
</body>